# Generated by Django 3.2.13 on 2022-04-18 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeleBot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='message',
            field=models.TextField(help_text='Enter a brief description of the book', max_length=1000, null=True),
        ),
    ]
