# Generated by Django 3.2.13 on 2022-04-18 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TeleBot', '0002_report_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='date_of_birth',
            new_name='report_date',
        ),
    ]
