# Generated by Django 3.2.13 on 2022-04-18 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeleBot', '0003_rename_date_of_birth_report_report_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='users',
            field=models.ManyToManyField(help_text='Select a genre for this book', related_name='users', to='TeleBot.Person'),
        ),
    ]
