# Generated by Django 4.0.4 on 2022-04-19 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TeleBot', '0004_alter_project_users'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ('first_name',)},
        ),
    ]
