# Generated by Django 4.0.4 on 2022-04-20 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TeleBot', '0005_alter_person_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='responsible_user',
        ),
        migrations.RemoveField(
            model_name='project',
            name='users',
        ),
        migrations.RemoveField(
            model_name='report',
            name='project',
        ),
        migrations.RemoveField(
            model_name='report',
            name='user',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='Report',
        ),
    ]
